spring:
  application:
    name: personal_cloud_sync_test
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          results: TRACE
rclone:
  timeout-second: 5
executor-config:
  core-pool-size: 5
  keep-alive-time: 0
  queue-capacity: 100
  maximum-pool-size: 10
sync-job-scheduler:
  batch-size: 10
  running-interval: 30
