spring:
  application:
    name: personal_cloud_sync_dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

rclone:
  timeout-second: 3600
executor-config:
  core-pool-size: 5
  keep-alive-time: 0
  queue-capacity: 100
  maximum-pool-size: 10
sync-job-scheduler:
  batch-size: 10
  running-interval: 30
