spring:
  application:
    name: personal_cloud_sync_dev
  datasource:
    url: jdbc:mysql://localhost:3306/personal_sync_db_test
    username: root
    password: 12345
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true