spring:
  application:
    name: personal_cloud_sync
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
server:
  port: 20000
logging:
  level:
    org.flywaydb: info